### ISSUE TITLE
dimensions must be equal but are 64 and 8 for 'generator/e3d-lstm_10/mul_1' (op: Mul) witn input shape [8,64,64,1] [8, 64,64]

### ISSUE THREAD

**Issue by sjjlr** [google/e3d_lstm#4]
When I run the run.py and get the error:
ValueError: dimensions must be equal but are 64 and 8 for 'generator/e3d-lstm_10/mul_1' (op: Mul) witn input shape [8,64,64,1] [8, 64,64].
How to solve it?

**Comment by ManWingloeng** [comment]
This issue happen only with the patch size=1, in their test they use patch_size=4. @sjjlr

**Comment by roadjiang** [comment]
Thank you @ManWingloeng for resolving this issue.
